/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rdconnect.org.idcardmolgenis.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RDConnectIDCardMolgenis service. Represents a row in the &quot;rdconnect_RDConnectIDCardMolgenis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rdconnect.org.idcardmolgenis.model.impl.RDConnectIDCardMolgenisModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rdconnect.org.idcardmolgenis.model.impl.RDConnectIDCardMolgenisImpl}.
 * </p>
 *
 * @author suyeshamatya
 * @see RDConnectIDCardMolgenis
 * @see com.rdconnect.org.idcardmolgenis.model.impl.RDConnectIDCardMolgenisImpl
 * @see com.rdconnect.org.idcardmolgenis.model.impl.RDConnectIDCardMolgenisModelImpl
 * @generated
 */
public interface RDConnectIDCardMolgenisModel extends BaseModel<RDConnectIDCardMolgenis> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a r d connect i d card molgenis model instance should use the {@link RDConnectIDCardMolgenis} interface instead.
	 */

	/**
	 * Returns the primary key of this r d connect i d card molgenis.
	 *
	 * @return the primary key of this r d connect i d card molgenis
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this r d connect i d card molgenis.
	 *
	 * @param primaryKey the primary key of this r d connect i d card molgenis
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this r d connect i d card molgenis.
	 *
	 * @return the ID of this r d connect i d card molgenis
	 */
	public long getId();

	/**
	 * Sets the ID of this r d connect i d card molgenis.
	 *
	 * @param id the ID of this r d connect i d card molgenis
	 */
	public void setId(long id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis rdConnectIDCardMolgenis);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis> toCacheModel();

	@Override
	public com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis toEscapedModel();

	@Override
	public com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}