/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rdconnect.org.idcardmolgenis.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis;
import com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenisModel;
import com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenisSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RDConnectIDCardMolgenis service. Represents a row in the &quot;rdconnect_RDConnectIDCardMolgenis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenisModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RDConnectIDCardMolgenisImpl}.
 * </p>
 *
 * @author suyeshamatya
 * @see RDConnectIDCardMolgenisImpl
 * @see com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis
 * @see com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenisModel
 * @generated
 */
@JSON(strict = true)
public class RDConnectIDCardMolgenisModelImpl extends BaseModelImpl<RDConnectIDCardMolgenis>
	implements RDConnectIDCardMolgenisModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a r d connect i d card molgenis model instance should use the {@link com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis} interface instead.
	 */
	public static final String TABLE_NAME = "rdconnect_RDConnectIDCardMolgenis";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table rdconnect_RDConnectIDCardMolgenis (id_ LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table rdconnect_RDConnectIDCardMolgenis";
	public static final String ORDER_BY_JPQL = " ORDER BY rdConnectIDCardMolgenis.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY rdconnect_RDConnectIDCardMolgenis.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RDConnectIDCardMolgenis toModel(
		RDConnectIDCardMolgenisSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RDConnectIDCardMolgenis model = new RDConnectIDCardMolgenisImpl();

		model.setId(soapModel.getId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RDConnectIDCardMolgenis> toModels(
		RDConnectIDCardMolgenisSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RDConnectIDCardMolgenis> models = new ArrayList<RDConnectIDCardMolgenis>(soapModels.length);

		for (RDConnectIDCardMolgenisSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis"));

	public RDConnectIDCardMolgenisModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RDConnectIDCardMolgenis.class;
	}

	@Override
	public String getModelClassName() {
		return RDConnectIDCardMolgenis.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RDConnectIDCardMolgenis.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RDConnectIDCardMolgenis toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RDConnectIDCardMolgenis)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RDConnectIDCardMolgenisImpl rdConnectIDCardMolgenisImpl = new RDConnectIDCardMolgenisImpl();

		rdConnectIDCardMolgenisImpl.setId(getId());

		rdConnectIDCardMolgenisImpl.resetOriginalValues();

		return rdConnectIDCardMolgenisImpl;
	}

	@Override
	public int compareTo(RDConnectIDCardMolgenis rdConnectIDCardMolgenis) {
		long primaryKey = rdConnectIDCardMolgenis.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RDConnectIDCardMolgenis)) {
			return false;
		}

		RDConnectIDCardMolgenis rdConnectIDCardMolgenis = (RDConnectIDCardMolgenis)obj;

		long primaryKey = rdConnectIDCardMolgenis.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RDConnectIDCardMolgenis> toCacheModel() {
		RDConnectIDCardMolgenisCacheModel rdConnectIDCardMolgenisCacheModel = new RDConnectIDCardMolgenisCacheModel();

		rdConnectIDCardMolgenisCacheModel.id = getId();

		return rdConnectIDCardMolgenisCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{id=");
		sb.append(getId());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append(
			"com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RDConnectIDCardMolgenis.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			RDConnectIDCardMolgenis.class
		};
	private long _id;
	private RDConnectIDCardMolgenis _escapedModel;
}