/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rdconnect.org.idcardmolgenis.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis;
import com.rdconnect.org.idcardmolgenis.service.RDConnectIDCardMolgenisLocalServiceUtil;

/**
 * The extended model base implementation for the RDConnectIDCardMolgenis service. Represents a row in the &quot;rdconnect_RDConnectIDCardMolgenis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RDConnectIDCardMolgenisImpl}.
 * </p>
 *
 * @author suyeshamatya
 * @see RDConnectIDCardMolgenisImpl
 * @see com.rdconnect.org.idcardmolgenis.model.RDConnectIDCardMolgenis
 * @generated
 */
public abstract class RDConnectIDCardMolgenisBaseImpl
	extends RDConnectIDCardMolgenisModelImpl implements RDConnectIDCardMolgenis {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a r d connect i d card molgenis model instance should use the {@link RDConnectIDCardMolgenis} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			RDConnectIDCardMolgenisLocalServiceUtil.addRDConnectIDCardMolgenis(this);
		}
		else {
			RDConnectIDCardMolgenisLocalServiceUtil.updateRDConnectIDCardMolgenis(this);
		}
	}
}