/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model;

import com.bcnet.portlet.biobank.service.persistence.SampleCollectionContactPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SampleCollectionContact service. Represents a row in the &quot;samplecollectioncontact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bcnet.portlet.biobank.model.impl.SampleCollectionContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bcnet.portlet.biobank.model.impl.SampleCollectionContactImpl}.
 * </p>
 *
 * @author suyama
 * @see SampleCollectionContact
 * @see com.bcnet.portlet.biobank.model.impl.SampleCollectionContactImpl
 * @see com.bcnet.portlet.biobank.model.impl.SampleCollectionContactModelImpl
 * @generated
 */
public interface SampleCollectionContactModel extends BaseModel<SampleCollectionContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample collection contact model instance should use the {@link SampleCollectionContact} interface instead.
	 */

	/**
	 * Returns the primary key of this sample collection contact.
	 *
	 * @return the primary key of this sample collection contact
	 */
	public SampleCollectionContactPK getPrimaryKey();

	/**
	 * Sets the primary key of this sample collection contact.
	 *
	 * @param primaryKey the primary key of this sample collection contact
	 */
	public void setPrimaryKey(SampleCollectionContactPK primaryKey);

	/**
	 * Returns the sample collection db ID of this sample collection contact.
	 *
	 * @return the sample collection db ID of this sample collection contact
	 */
	public long getSampleCollectionDbId();

	/**
	 * Sets the sample collection db ID of this sample collection contact.
	 *
	 * @param sampleCollectionDbId the sample collection db ID of this sample collection contact
	 */
	public void setSampleCollectionDbId(long sampleCollectionDbId);

	/**
	 * Returns the user ID of this sample collection contact.
	 *
	 * @return the user ID of this sample collection contact
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sample collection contact.
	 *
	 * @param userId the user ID of this sample collection contact
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sample collection contact.
	 *
	 * @return the user uuid of this sample collection contact
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sample collection contact.
	 *
	 * @param userUuid the user uuid of this sample collection contact
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the main contact of this sample collection contact.
	 *
	 * @return the main contact of this sample collection contact
	 */
	public boolean getMainContact();

	/**
	 * Returns <code>true</code> if this sample collection contact is main contact.
	 *
	 * @return <code>true</code> if this sample collection contact is main contact; <code>false</code> otherwise
	 */
	public boolean isMainContact();

	/**
	 * Sets whether this sample collection contact is main contact.
	 *
	 * @param mainContact the main contact of this sample collection contact
	 */
	public void setMainContact(boolean mainContact);

	/**
	 * Returns the sample collection owner of this sample collection contact.
	 *
	 * @return the sample collection owner of this sample collection contact
	 */
	public boolean getSampleCollectionOwner();

	/**
	 * Returns <code>true</code> if this sample collection contact is sample collection owner.
	 *
	 * @return <code>true</code> if this sample collection contact is sample collection owner; <code>false</code> otherwise
	 */
	public boolean isSampleCollectionOwner();

	/**
	 * Sets whether this sample collection contact is sample collection owner.
	 *
	 * @param sampleCollectionOwner the sample collection owner of this sample collection contact
	 */
	public void setSampleCollectionOwner(boolean sampleCollectionOwner);

	/**
	 * Returns the sample collection editor of this sample collection contact.
	 *
	 * @return the sample collection editor of this sample collection contact
	 */
	public boolean getSampleCollectionEditor();

	/**
	 * Returns <code>true</code> if this sample collection contact is sample collection editor.
	 *
	 * @return <code>true</code> if this sample collection contact is sample collection editor; <code>false</code> otherwise
	 */
	public boolean isSampleCollectionEditor();

	/**
	 * Sets whether this sample collection contact is sample collection editor.
	 *
	 * @param sampleCollectionEditor the sample collection editor of this sample collection contact
	 */
	public void setSampleCollectionEditor(boolean sampleCollectionEditor);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SampleCollectionContact sampleCollectionContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SampleCollectionContact> toCacheModel();

	@Override
	public SampleCollectionContact toEscapedModel();

	@Override
	public SampleCollectionContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}