/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SampleCollectionAttributeLists service. Represents a row in the &quot;samplecollectionattributelists&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bcnet.portlet.biobank.model.impl.SampleCollectionAttributeListsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bcnet.portlet.biobank.model.impl.SampleCollectionAttributeListsImpl}.
 * </p>
 *
 * @author suyama
 * @see SampleCollectionAttributeLists
 * @see com.bcnet.portlet.biobank.model.impl.SampleCollectionAttributeListsImpl
 * @see com.bcnet.portlet.biobank.model.impl.SampleCollectionAttributeListsModelImpl
 * @generated
 */
public interface SampleCollectionAttributeListsModel extends BaseModel<SampleCollectionAttributeLists> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample collection attribute lists model instance should use the {@link SampleCollectionAttributeLists} interface instead.
	 */

	/**
	 * Returns the primary key of this sample collection attribute lists.
	 *
	 * @return the primary key of this sample collection attribute lists
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sample collection attribute lists.
	 *
	 * @param primaryKey the primary key of this sample collection attribute lists
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sample collection attribute lists ID of this sample collection attribute lists.
	 *
	 * @return the sample collection attribute lists ID of this sample collection attribute lists
	 */
	public long getSampleCollectionAttributeListsId();

	/**
	 * Sets the sample collection attribute lists ID of this sample collection attribute lists.
	 *
	 * @param sampleCollectionAttributeListsId the sample collection attribute lists ID of this sample collection attribute lists
	 */
	public void setSampleCollectionAttributeListsId(
		long sampleCollectionAttributeListsId);

	/**
	 * Returns the sample collection db ID of this sample collection attribute lists.
	 *
	 * @return the sample collection db ID of this sample collection attribute lists
	 */
	public long getSampleCollectionDbId();

	/**
	 * Sets the sample collection db ID of this sample collection attribute lists.
	 *
	 * @param sampleCollectionDbId the sample collection db ID of this sample collection attribute lists
	 */
	public void setSampleCollectionDbId(long sampleCollectionDbId);

	/**
	 * Returns the attribute list name of this sample collection attribute lists.
	 *
	 * @return the attribute list name of this sample collection attribute lists
	 */
	@AutoEscape
	public String getAttributeListName();

	/**
	 * Sets the attribute list name of this sample collection attribute lists.
	 *
	 * @param attributeListName the attribute list name of this sample collection attribute lists
	 */
	public void setAttributeListName(String attributeListName);

	/**
	 * Returns the attribute list value of this sample collection attribute lists.
	 *
	 * @return the attribute list value of this sample collection attribute lists
	 */
	@AutoEscape
	public String getAttributeListValue();

	/**
	 * Sets the attribute list value of this sample collection attribute lists.
	 *
	 * @param attributeListValue the attribute list value of this sample collection attribute lists
	 */
	public void setAttributeListValue(String attributeListValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		SampleCollectionAttributeLists sampleCollectionAttributeLists);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SampleCollectionAttributeLists> toCacheModel();

	@Override
	public SampleCollectionAttributeLists toEscapedModel();

	@Override
	public SampleCollectionAttributeLists toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}