/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SampleImportLog service. Represents a row in the &quot;sampleimportlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bcnet.portlet.biobank.model.impl.SampleImportLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bcnet.portlet.biobank.model.impl.SampleImportLogImpl}.
 * </p>
 *
 * @author suyama
 * @see SampleImportLog
 * @see com.bcnet.portlet.biobank.model.impl.SampleImportLogImpl
 * @see com.bcnet.portlet.biobank.model.impl.SampleImportLogModelImpl
 * @generated
 */
public interface SampleImportLogModel extends BaseModel<SampleImportLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample import log model instance should use the {@link SampleImportLog} interface instead.
	 */

	/**
	 * Returns the primary key of this sample import log.
	 *
	 * @return the primary key of this sample import log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sample import log.
	 *
	 * @param primaryKey the primary key of this sample import log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sample import log.
	 *
	 * @return the uuid of this sample import log
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this sample import log.
	 *
	 * @param uuid the uuid of this sample import log
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the import ID of this sample import log.
	 *
	 * @return the import ID of this sample import log
	 */
	public long getImportId();

	/**
	 * Sets the import ID of this sample import log.
	 *
	 * @param importId the import ID of this sample import log
	 */
	public void setImportId(long importId);

	/**
	 * Returns the file name of this sample import log.
	 *
	 * @return the file name of this sample import log
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this sample import log.
	 *
	 * @param fileName the file name of this sample import log
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the user ID of this sample import log.
	 *
	 * @return the user ID of this sample import log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sample import log.
	 *
	 * @param userId the user ID of this sample import log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sample import log.
	 *
	 * @return the user uuid of this sample import log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sample import log.
	 *
	 * @param userUuid the user uuid of this sample import log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the date of import of this sample import log.
	 *
	 * @return the date of import of this sample import log
	 */
	public Date getDateOfImport();

	/**
	 * Sets the date of import of this sample import log.
	 *
	 * @param dateOfImport the date of import of this sample import log
	 */
	public void setDateOfImport(Date dateOfImport);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.bcnet.portlet.biobank.model.SampleImportLog sampleImportLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.bcnet.portlet.biobank.model.SampleImportLog> toCacheModel();

	@Override
	public com.bcnet.portlet.biobank.model.SampleImportLog toEscapedModel();

	@Override
	public com.bcnet.portlet.biobank.model.SampleImportLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}