/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model.impl;

import com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster;
import com.bcnet.portlet.biobank.service.SampleCollectionAttributeListsMasterLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SampleCollectionAttributeListsMaster service. Represents a row in the &quot;samplecollectionattributelistsmaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleCollectionAttributeListsMasterImpl}.
 * </p>
 *
 * @author suyama
 * @see SampleCollectionAttributeListsMasterImpl
 * @see com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster
 * @generated
 */
public abstract class SampleCollectionAttributeListsMasterBaseImpl
	extends SampleCollectionAttributeListsMasterModelImpl
	implements SampleCollectionAttributeListsMaster {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample collection attribute lists master model instance should use the {@link SampleCollectionAttributeListsMaster} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SampleCollectionAttributeListsMasterLocalServiceUtil.addSampleCollectionAttributeListsMaster(this);
		}
		else {
			SampleCollectionAttributeListsMasterLocalServiceUtil.updateSampleCollectionAttributeListsMaster(this);
		}
	}
}