/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bcnet.portlet.biobank.model.impl;

import com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster;
import com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMasterModel;
import com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMasterSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SampleCollectionAttributeListsMaster service. Represents a row in the &quot;samplecollectionattributelistsmaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleCollectionAttributeListsMasterImpl}.
 * </p>
 *
 * @author suyama
 * @see SampleCollectionAttributeListsMasterImpl
 * @see com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster
 * @see com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMasterModel
 * @generated
 */
@JSON(strict = true)
public class SampleCollectionAttributeListsMasterModelImpl extends BaseModelImpl<SampleCollectionAttributeListsMaster>
	implements SampleCollectionAttributeListsMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample collection attribute lists master model instance should use the {@link com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster} interface instead.
	 */
	public static final String TABLE_NAME = "samplecollectionattributelistsmaster";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sampleCollectionAttributeListsMasterId", Types.BIGINT },
			{ "attributeListName", Types.VARCHAR },
			{ "attributeListValue", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table samplecollectionattributelistsmaster (sampleCollectionAttributeListsMasterId LONG not null primary key,attributeListName VARCHAR(75) null,attributeListValue VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table samplecollectionattributelistsmaster";
	public static final String ORDER_BY_JPQL = " ORDER BY sampleCollectionAttributeListsMaster.sampleCollectionAttributeListsMasterId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY samplecollectionattributelistsmaster.sampleCollectionAttributeListsMasterId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SampleCollectionAttributeListsMaster toModel(
		SampleCollectionAttributeListsMasterSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SampleCollectionAttributeListsMaster model = new SampleCollectionAttributeListsMasterImpl();

		model.setSampleCollectionAttributeListsMasterId(soapModel.getSampleCollectionAttributeListsMasterId());
		model.setAttributeListName(soapModel.getAttributeListName());
		model.setAttributeListValue(soapModel.getAttributeListValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SampleCollectionAttributeListsMaster> toModels(
		SampleCollectionAttributeListsMasterSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SampleCollectionAttributeListsMaster> models = new ArrayList<SampleCollectionAttributeListsMaster>(soapModels.length);

		for (SampleCollectionAttributeListsMasterSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster"));

	public SampleCollectionAttributeListsMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sampleCollectionAttributeListsMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSampleCollectionAttributeListsMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sampleCollectionAttributeListsMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SampleCollectionAttributeListsMaster.class;
	}

	@Override
	public String getModelClassName() {
		return SampleCollectionAttributeListsMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("sampleCollectionAttributeListsMasterId",
			getSampleCollectionAttributeListsMasterId());
		attributes.put("attributeListName", getAttributeListName());
		attributes.put("attributeListValue", getAttributeListValue());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long sampleCollectionAttributeListsMasterId = (Long)attributes.get(
				"sampleCollectionAttributeListsMasterId");

		if (sampleCollectionAttributeListsMasterId != null) {
			setSampleCollectionAttributeListsMasterId(sampleCollectionAttributeListsMasterId);
		}

		String attributeListName = (String)attributes.get("attributeListName");

		if (attributeListName != null) {
			setAttributeListName(attributeListName);
		}

		String attributeListValue = (String)attributes.get("attributeListValue");

		if (attributeListValue != null) {
			setAttributeListValue(attributeListValue);
		}
	}

	@JSON
	@Override
	public long getSampleCollectionAttributeListsMasterId() {
		return _sampleCollectionAttributeListsMasterId;
	}

	@Override
	public void setSampleCollectionAttributeListsMasterId(
		long sampleCollectionAttributeListsMasterId) {
		_sampleCollectionAttributeListsMasterId = sampleCollectionAttributeListsMasterId;
	}

	@JSON
	@Override
	public String getAttributeListName() {
		if (_attributeListName == null) {
			return StringPool.BLANK;
		}
		else {
			return _attributeListName;
		}
	}

	@Override
	public void setAttributeListName(String attributeListName) {
		_attributeListName = attributeListName;
	}

	@JSON
	@Override
	public String getAttributeListValue() {
		if (_attributeListValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _attributeListValue;
		}
	}

	@Override
	public void setAttributeListValue(String attributeListValue) {
		_attributeListValue = attributeListValue;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SampleCollectionAttributeListsMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SampleCollectionAttributeListsMaster toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SampleCollectionAttributeListsMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SampleCollectionAttributeListsMasterImpl sampleCollectionAttributeListsMasterImpl =
			new SampleCollectionAttributeListsMasterImpl();

		sampleCollectionAttributeListsMasterImpl.setSampleCollectionAttributeListsMasterId(getSampleCollectionAttributeListsMasterId());
		sampleCollectionAttributeListsMasterImpl.setAttributeListName(getAttributeListName());
		sampleCollectionAttributeListsMasterImpl.setAttributeListValue(getAttributeListValue());

		sampleCollectionAttributeListsMasterImpl.resetOriginalValues();

		return sampleCollectionAttributeListsMasterImpl;
	}

	@Override
	public int compareTo(
		SampleCollectionAttributeListsMaster sampleCollectionAttributeListsMaster) {
		long primaryKey = sampleCollectionAttributeListsMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SampleCollectionAttributeListsMaster)) {
			return false;
		}

		SampleCollectionAttributeListsMaster sampleCollectionAttributeListsMaster =
			(SampleCollectionAttributeListsMaster)obj;

		long primaryKey = sampleCollectionAttributeListsMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SampleCollectionAttributeListsMaster> toCacheModel() {
		SampleCollectionAttributeListsMasterCacheModel sampleCollectionAttributeListsMasterCacheModel =
			new SampleCollectionAttributeListsMasterCacheModel();

		sampleCollectionAttributeListsMasterCacheModel.sampleCollectionAttributeListsMasterId = getSampleCollectionAttributeListsMasterId();

		sampleCollectionAttributeListsMasterCacheModel.attributeListName = getAttributeListName();

		String attributeListName = sampleCollectionAttributeListsMasterCacheModel.attributeListName;

		if ((attributeListName != null) && (attributeListName.length() == 0)) {
			sampleCollectionAttributeListsMasterCacheModel.attributeListName = null;
		}

		sampleCollectionAttributeListsMasterCacheModel.attributeListValue = getAttributeListValue();

		String attributeListValue = sampleCollectionAttributeListsMasterCacheModel.attributeListValue;

		if ((attributeListValue != null) && (attributeListValue.length() == 0)) {
			sampleCollectionAttributeListsMasterCacheModel.attributeListValue = null;
		}

		return sampleCollectionAttributeListsMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{sampleCollectionAttributeListsMasterId=");
		sb.append(getSampleCollectionAttributeListsMasterId());
		sb.append(", attributeListName=");
		sb.append(getAttributeListName());
		sb.append(", attributeListValue=");
		sb.append(getAttributeListValue());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"com.bcnet.portlet.biobank.model.SampleCollectionAttributeListsMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sampleCollectionAttributeListsMasterId</column-name><column-value><![CDATA[");
		sb.append(getSampleCollectionAttributeListsMasterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attributeListName</column-name><column-value><![CDATA[");
		sb.append(getAttributeListName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attributeListValue</column-name><column-value><![CDATA[");
		sb.append(getAttributeListValue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SampleCollectionAttributeListsMaster.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SampleCollectionAttributeListsMaster.class
		};
	private long _sampleCollectionAttributeListsMasterId;
	private String _attributeListName;
	private String _attributeListValue;
	private SampleCollectionAttributeListsMaster _escapedModel;
}